---
- name: Ubuntu Performance Fine-Tune Playbook
  hosts: all
  become: yes
  gather_facts: yes
  
  vars:
    timezone: "Europe/Istanbul"
    net_interface: "ens160"
    sysctl_conf: "/etc/sysctl.conf"
    limits_conf: "/etc/security/limits.conf"
    bashrc_conf: "/etc/bash.bashrc"
    journald_conf: "/etc/systemd/journald.conf"
    backup_date: "{{ ansible_date_time.date }}"

  tasks:
    - name: Stop and disable apt-daily timers
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - apt-daily.timer
        - apt-daily-upgrade.timer
      ignore_errors: yes

    - name: Stop and disable unattended-upgrades
      systemd:
        name: unattended-upgrades
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Disable APT automatic updates
      copy:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        content: |
          APT::Periodic::Update-Package-Lists "0";
          APT::Periodic::Unattended-Upgrade "0";
        mode: '0644'

    - name: Set timezone
      timezone:
        name: "{{ timezone }}"

    - name: Enable NTP synchronization
      command: timedatectl set-ntp true
      changed_when: false

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Check if network interface exists
      shell: ip link show {{ net_interface }}
      register: interface_check
      failed_when: false
      changed_when: false

    - name: Disable TX offload on network interface
      command: ethtool -K {{ net_interface }} tx off
      when: interface_check.rc == 0
      ignore_errors: yes
      changed_when: false

    - name: Disable TX checksum IP generic on network interface
      command: ethtool -K {{ net_interface }} tx-checksum-ip-generic off
      when: interface_check.rc == 0
      ignore_errors: yes
      changed_when: false

    - name: Backup sysctl.conf
      copy:
        src: "{{ sysctl_conf }}"
        dest: "{{ sysctl_conf }}.bak.{{ backup_date }}"
        remote_src: yes
        backup: no

    - name: Configure kernel parameters in sysctl.conf
      blockinfile:
        path: "{{ sysctl_conf }}"
        block: |
          # Virtual Memory Management
          vm.swappiness = 10
          vm.vfs_cache_pressure = 50
          
          # Network Performance (High Traffic)
          net.core.rmem_max = 16777216
          net.core.wmem_max = 16777216
          net.ipv4.tcp_rmem = 4096 87380 16777216
          net.ipv4.tcp_wmem = 4096 65536 16777216
          net.ipv4.tcp_tw_reuse = 1
          
          # Connection tracking table size
          net.netfilter.nf_conntrack_max = 262144
          
          # File descriptor ve inotify limitleri
          fs.file-max = 2097152
          fs.inotify.max_user_watches = 524288
          fs.inotify.max_user_instances = 512
          
          # Shared memory
          kernel.shmmax = 68719476736
          kernel.shmall = 4294967296
        marker: "# {mark} ANSIBLE MANAGED BLOCK - Performance Tuning"
        create: no

    - name: Apply sysctl parameters
      command: sysctl -p
      changed_when: false

    - name: Backup limits.conf
      copy:
        src: "{{ limits_conf }}"
        dest: "{{ limits_conf }}.bak.{{ backup_date }}"
        remote_src: yes
        backup: no

    - name: Configure system resource limits
      blockinfile:
        path: "{{ limits_conf }}"
        block: |
          * soft nofile 65535
          * hard nofile 65535
        marker: "# {mark} ANSIBLE MANAGED BLOCK - Resource Limits"
        create: no

    - name: Backup bash.bashrc
      copy:
        src: "{{ bashrc_conf }}"
        dest: "{{ bashrc_conf }}.bak.{{ backup_date }}"
        remote_src: yes
        backup: no

    - name: Configure bash history settings
      blockinfile:
        path: "{{ bashrc_conf }}"
        block: |
          # History ayarları
          export HISTSIZE=10000
          export HISTFILESIZE=20000
          export HISTTIMEFORMAT="%F %T "
          export HISTCONTROL=ignoredups:erasedups
          shopt -s histappend
          PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - History Settings"
        create: no

    - name: Backup journald.conf
      copy:
        src: "{{ journald_conf }}"
        dest: "{{ journald_conf }}.bak.{{ backup_date }}"
        remote_src: yes
        backup: no

    - name: Configure journald log limits
      lineinfile:
        path: "{{ journald_conf }}"
        regexp: "^#?{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
        state: present
      loop:
        - { key: 'SystemMaxUse', value: '500M' }
        - { key: 'SystemMaxFileSize', value: '50M' }
        - { key: 'MaxRetentionSec', value: '1month' }

    - name: Restart systemd-journald
      systemd:
        name: systemd-journald
        state: restarted

    - name: Install monitoring tools
      apt:
        name:
          - htop
          - iotop
          - nethogs
          - ncdu
          - dstat
        state: present
        update_cache: yes

    - name: Check disk type and set I/O scheduler (immediate)
      shell: |
        if [ -b /sys/block/sda/queue/scheduler ]; then
          echo "none" > /sys/block/sda/queue/scheduler 2>/dev/null || echo "noop" > /sys/block/sda/queue/scheduler 2>/dev/null
        fi
      changed_when: false
      ignore_errors: yes

    - name: Create persistent I/O scheduler rules
      copy:
        dest: /etc/udev/rules.d/60-scheduler.rules
        content: |
          ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/rotational}=="0", ATTR{queue/scheduler}="none"
          ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/rotational}=="1", ATTR{queue/scheduler}="mq-deadline"
        mode: '0644'

    - name: Make network interface settings persistent
      copy:
        dest: /etc/network/if-up.d/ethtool-settings
        content: |
          #!/bin/sh
          ethtool -K {{ net_interface }} tx off
          ethtool -K {{ net_interface }} tx-checksum-ip-generic off
        mode: '0755'
      when: interface_check.rc == 0

    - name: Display completion message
      debug:
        msg: "Fine-tune işlemleri tamamlandı. Değişikliklerin tam olarak aktif olması için sistemi yeniden başlatmanız önerilir."